name: jaganetra
description: "Aplikasi asisten pribadi untuk mengingatkan jadwal tetes mata dan minum obat pasca operasi katarak."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Ikon bawaan iOS
  cupertino_icons: ^1.0.8
  
  # --- LIBRARY TAMBAHAN UNTUK JAGANETRA ---
  # Untuk notifikasi lokal (alarm)
  flutter_local_notifications: ^17.0.0
  # Untuk pengaturan zona waktu (WIB/dll)
  timezone: ^0.9.0
  # Untuk format tanggal yang rapi
  intl: ^0.18.0
  # Untuk Font mewah (Google Fonts)
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true